version: "3.8"

services:
  xhs_pic_download:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xhs_pic_download
    env_file:
      - xhs.env
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: xhs_tunnel
    restart: always
    command: tunnel run
    env_file:
      - cf.env
